language: php
php:
  - 7.4
  - 8.0
  - 8.1

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run -v
  - vendor/bin/phpcs --standard=PSR2 src/
  - vendor/bin/phpstan analyse src/ --level 5
